<?php

return[
    "buyer"=>["private_experienced"=>"0","corporate"=>"1","intermediary"=>"2"],
    "inactive"=>2,
    "active"=>1,
    "pending"=>3,
    "doctorDefaultPassword"=>"Doctor@123",
    "roleDoctor"=>"Doctor",
    'currency_symbol' => '$',
    'product_id'=>"prod_J95Ema8APTgcYZ",
    'dev_product_id'=>'prod_J90goHH22vwx9m',
    "local_env"=>"local",
    "first_plan"=>"9900",
    "second_plan"=>"12900",
    "third_plan"=>"17500",
    "fourth_plan"=>"22900",
    "individual_listing_plan_price"=>"2995",
    "local_product_id"=>"prod_J4piMtGXn4lcVT",
    "local_ip_addr"=>"127.0.0.1",
    "default_image"=>'images/Logo-main.png',
    "price_range"=>["1","2","3","4","5","6",'un'],
    "undisclosed"=>"Undisclosed",
    "importSuccess"=>"File imported successfully",
    "active_campaign_token"=>"0b3b049fe0c8cbdd63ee7e8c6b577e19d99aafdb9009a17af626483fcde036b606f020c8",
    "google_api_key"=>"AIzaSyAOITb2z8sXiFDdy4RTMlWycfjC2AYgAwA",
    "listing_already_saved"=>"Listing already saved you can't save more than one listing",
    "saved_for_later"=>"Record has been saved for later use",
    "qa_server"=>"http://btapp-qa.zapbuild.in/",
    "dev_server"=>"http://btapp-dev.zapbuild.in/",
    "type_field"=>1,
    "type_radio"=>2,
    "type_checkbox"=>3,
    "type_selectbox"=>4,
    "type_textarea"=>5,
    "starting_id"=>10000,
    "type-area"=>"area",
    "type-category"=>"category",
    "type-subcategory"=>"sub-category",
    "speciality"=>["0"=>"Cardiology - Non Interventional","1"=>"Corneal Transplant.","2"=>"General Surgery","3"=>"Infectious Diseases",
    "4"=>"In-Vitro Fertilisation (IVF)","5"=>"Laboratory Medicine.","6"=>"Medical Gastroenterology"],
    "personal_email"=>"sahildhawan74@gmail.com",
];
